on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.0
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: file/file
        path: node_modules/c-libmagic
    - run: |
        apt update
        apt install --yes autoconf automake libtool
        bash build.sh
    - uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
    - run: |
        node -e "require('./dist/magic-js').MagicBinding.init('./dist/magic.mgc', 0);"
